version: "3"
networks:
  app-php:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    networks:
      - app-php
    ports:
      - 9003:9000
    volumes:
      - ./code/:/srv/code
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - 5005:80
    volumes_from:
      - app
    restart: always
    networks:
      - app-php